# Generated by Django 4.1.7 on 2023-04-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('userID', models.CharField(max_length=255)),
                ('placeID', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('food_rating', models.CharField(max_length=255)),
                ('service_rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
