# Generated by Django 4.1.7 on 2023-04-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_mymodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='service_rating',
        ),
    ]
