# Generated by Django 4.1.7 on 2023-04-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_mymodel_service_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=255)),
                ('placeID', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('food_rating', models.CharField(max_length=255)),
                ('service_rating', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
