# Generated by Django 4.1.7 on 2023-04-09 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
