# Generated by Django 4.1.7 on 2023-04-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurent',
            name='total_rating',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
